/*
RezKit Tours Manager

Testing HolidayVersionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package tourmanager

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/rezkit/tour-manager-go"
)

func Test_tourmanager_HolidayVersionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HolidayVersionsAPIService CreateHolidayVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var holidayId string

		resp, httpRes, err := apiClient.HolidayVersionsAPI.CreateHolidayVersion(context.Background(), holidayId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HolidayVersionsAPIService DeleteHolidayVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var holidayId string
		var versionId string

		httpRes, err := apiClient.HolidayVersionsAPI.DeleteHolidayVersion(context.Background(), holidayId, versionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HolidayVersionsAPIService GetHolidayVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var holidayId string
		var versionId string

		resp, httpRes, err := apiClient.HolidayVersionsAPI.GetHolidayVersion(context.Background(), holidayId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HolidayVersionsAPIService ListHolidayVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var holidayId string

		resp, httpRes, err := apiClient.HolidayVersionsAPI.ListHolidayVersions(context.Background(), holidayId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HolidayVersionsAPIService RestoreHolidayVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var holidayId string
		var versionId string

		resp, httpRes, err := apiClient.HolidayVersionsAPI.RestoreHolidayVersion(context.Background(), holidayId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HolidayVersionsAPIService UpdateHolidayVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var holidayId string
		var versionId string

		resp, httpRes, err := apiClient.HolidayVersionsAPI.UpdateHolidayVersion(context.Background(), holidayId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
