/*
RezKit Tours Manager

Testing DeparturesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package tourmanager

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/rezkit/tour-manager-go"
)

func Test_tourmanager_DeparturesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DeparturesAPIService CreateDeparture", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DeparturesAPI.CreateDeparture(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeparturesAPIService DeleteDeparture", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var departure string

		httpRes, err := apiClient.DeparturesAPI.DeleteDeparture(context.Background(), departure).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeparturesAPIService GetDeparture", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var departure string

		resp, httpRes, err := apiClient.DeparturesAPI.GetDeparture(context.Background(), departure).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeparturesAPIService ListDepartures", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DeparturesAPI.ListDepartures(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeparturesAPIService UpdateDeparture", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var departure string

		resp, httpRes, err := apiClient.DeparturesAPI.UpdateDeparture(context.Background(), departure).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
