/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// ElementsAPIService ElementsAPI service
type ElementsAPIService service

type ApiCreateElementRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	version string
	createElementRequest *CreateElementRequest
}

func (r ApiCreateElementRequest) CreateElementRequest(createElementRequest CreateElementRequest) ApiCreateElementRequest {
	r.createElementRequest = &createElementRequest
	return r
}

func (r ApiCreateElementRequest) Execute() (*Element, *http.Response, error) {
	return r.ApiService.CreateElementExecute(r)
}

/*
CreateElement Create Element

Create a new Element

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param version Version ID
 @return ApiCreateElementRequest
*/
func (a *ElementsAPIService) CreateElement(ctx context.Context, version string) ApiCreateElementRequest {
	return ApiCreateElementRequest{
		ApiService: a,
		ctx: ctx,
		version: version,
	}
}

// Execute executes the request
//  @return Element
func (a *ElementsAPIService) CreateElementExecute(r ApiCreateElementRequest) (*Element, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Element
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.CreateElement")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/versions/{version}/elements"
	localVarPath = strings.Replace(localVarPath, "{"+"version"+"}", url.PathEscape(parameterValueToString(r.version, "version")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.version) < 26 {
		return localVarReturnValue, nil, reportError("version must have at least 26 elements")
	}
	if strlen(r.version) > 26 {
		return localVarReturnValue, nil, reportError("version must have less than 26 elements")
	}
	if r.createElementRequest == nil {
		return localVarReturnValue, nil, reportError("createElementRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createElementRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v InlineObject2
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v InlineObject3
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateOptionRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	element string
	elementOptionCreate *ElementOptionCreate
}

func (r ApiCreateOptionRequest) ElementOptionCreate(elementOptionCreate ElementOptionCreate) ApiCreateOptionRequest {
	r.elementOptionCreate = &elementOptionCreate
	return r
}

func (r ApiCreateOptionRequest) Execute() (*ElementOptionProperties, *http.Response, error) {
	return r.ApiService.CreateOptionExecute(r)
}

/*
CreateOption Create Option

Create a new Element Option

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param element Element ID
 @return ApiCreateOptionRequest
*/
func (a *ElementsAPIService) CreateOption(ctx context.Context, element string) ApiCreateOptionRequest {
	return ApiCreateOptionRequest{
		ApiService: a,
		ctx: ctx,
		element: element,
	}
}

// Execute executes the request
//  @return ElementOptionProperties
func (a *ElementsAPIService) CreateOptionExecute(r ApiCreateOptionRequest) (*ElementOptionProperties, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ElementOptionProperties
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.CreateOption")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/elements/{element}/options"
	localVarPath = strings.Replace(localVarPath, "{"+"element"+"}", url.PathEscape(parameterValueToString(r.element, "element")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.element) < 26 {
		return localVarReturnValue, nil, reportError("element must have at least 26 elements")
	}
	if strlen(r.element) > 26 {
		return localVarReturnValue, nil, reportError("element must have less than 26 elements")
	}
	if r.elementOptionCreate == nil {
		return localVarReturnValue, nil, reportError("elementOptionCreate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.elementOptionCreate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v InlineObject3
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteElementRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	version string
	element string
}

func (r ApiDeleteElementRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteElementExecute(r)
}

/*
DeleteElement Delete Element

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param version Version ID
 @param element Element ID
 @return ApiDeleteElementRequest
*/
func (a *ElementsAPIService) DeleteElement(ctx context.Context, version string, element string) ApiDeleteElementRequest {
	return ApiDeleteElementRequest{
		ApiService: a,
		ctx: ctx,
		version: version,
		element: element,
	}
}

// Execute executes the request
func (a *ElementsAPIService) DeleteElementExecute(r ApiDeleteElementRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.DeleteElement")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/versions/{version}/elements/{element}"
	localVarPath = strings.Replace(localVarPath, "{"+"version"+"}", url.PathEscape(parameterValueToString(r.version, "version")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"element"+"}", url.PathEscape(parameterValueToString(r.element, "element")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.version) < 26 {
		return nil, reportError("version must have at least 26 elements")
	}
	if strlen(r.version) > 26 {
		return nil, reportError("version must have less than 26 elements")
	}
	if strlen(r.element) < 26 {
		return nil, reportError("element must have at least 26 elements")
	}
	if strlen(r.element) > 26 {
		return nil, reportError("element must have less than 26 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiDeleteOptionRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	element string
	option string
}

func (r ApiDeleteOptionRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteOptionExecute(r)
}

/*
DeleteOption Delete Option

Delete an Option

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param element Element ID
 @param option Option ID
 @return ApiDeleteOptionRequest
*/
func (a *ElementsAPIService) DeleteOption(ctx context.Context, element string, option string) ApiDeleteOptionRequest {
	return ApiDeleteOptionRequest{
		ApiService: a,
		ctx: ctx,
		element: element,
		option: option,
	}
}

// Execute executes the request
func (a *ElementsAPIService) DeleteOptionExecute(r ApiDeleteOptionRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.DeleteOption")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/elements/{element}/options/{option}"
	localVarPath = strings.Replace(localVarPath, "{"+"element"+"}", url.PathEscape(parameterValueToString(r.element, "element")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"option"+"}", url.PathEscape(parameterValueToString(r.option, "option")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.element) < 26 {
		return nil, reportError("element must have at least 26 elements")
	}
	if strlen(r.element) > 26 {
		return nil, reportError("element must have less than 26 elements")
	}
	if strlen(r.option) < 26 {
		return nil, reportError("option must have at least 26 elements")
	}
	if strlen(r.option) > 26 {
		return nil, reportError("option must have less than 26 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetElementRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	version string
	element string
}

func (r ApiGetElementRequest) Execute() (*Element, *http.Response, error) {
	return r.ApiService.GetElementExecute(r)
}

/*
GetElement Get Element

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param version Version ID
 @param element Element ID
 @return ApiGetElementRequest
*/
func (a *ElementsAPIService) GetElement(ctx context.Context, version string, element string) ApiGetElementRequest {
	return ApiGetElementRequest{
		ApiService: a,
		ctx: ctx,
		version: version,
		element: element,
	}
}

// Execute executes the request
//  @return Element
func (a *ElementsAPIService) GetElementExecute(r ApiGetElementRequest) (*Element, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Element
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.GetElement")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/versions/{version}/elements/{element}"
	localVarPath = strings.Replace(localVarPath, "{"+"version"+"}", url.PathEscape(parameterValueToString(r.version, "version")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"element"+"}", url.PathEscape(parameterValueToString(r.element, "element")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.version) < 26 {
		return localVarReturnValue, nil, reportError("version must have at least 26 elements")
	}
	if strlen(r.version) > 26 {
		return localVarReturnValue, nil, reportError("version must have less than 26 elements")
	}
	if strlen(r.element) < 26 {
		return localVarReturnValue, nil, reportError("element must have at least 26 elements")
	}
	if strlen(r.element) > 26 {
		return localVarReturnValue, nil, reportError("element must have less than 26 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v InlineObject2
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetOptionRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	element string
	option string
}

func (r ApiGetOptionRequest) Execute() (*ElementOptionProperties, *http.Response, error) {
	return r.ApiService.GetOptionExecute(r)
}

/*
GetOption Get Option

Get a single element option

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param element Element ID
 @param option Option ID
 @return ApiGetOptionRequest
*/
func (a *ElementsAPIService) GetOption(ctx context.Context, element string, option string) ApiGetOptionRequest {
	return ApiGetOptionRequest{
		ApiService: a,
		ctx: ctx,
		element: element,
		option: option,
	}
}

// Execute executes the request
//  @return ElementOptionProperties
func (a *ElementsAPIService) GetOptionExecute(r ApiGetOptionRequest) (*ElementOptionProperties, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ElementOptionProperties
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.GetOption")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/elements/{element}/options/{option}"
	localVarPath = strings.Replace(localVarPath, "{"+"element"+"}", url.PathEscape(parameterValueToString(r.element, "element")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"option"+"}", url.PathEscape(parameterValueToString(r.option, "option")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.element) < 26 {
		return localVarReturnValue, nil, reportError("element must have at least 26 elements")
	}
	if strlen(r.element) > 26 {
		return localVarReturnValue, nil, reportError("element must have less than 26 elements")
	}
	if strlen(r.option) < 26 {
		return localVarReturnValue, nil, reportError("option must have at least 26 elements")
	}
	if strlen(r.option) > 26 {
		return localVarReturnValue, nil, reportError("option must have less than 26 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "applciation/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v InlineObject2
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListElementsRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	version string
	name *string
	page *int32
	limit *int32
	order *SortOrder
	sort *string
	trash *int32
	published *int32
}

// Filter elements by name (contains)
func (r ApiListElementsRequest) Name(name string) ApiListElementsRequest {
	r.name = &name
	return r
}

// Page number
func (r ApiListElementsRequest) Page(page int32) ApiListElementsRequest {
	r.page = &page
	return r
}

// Maximum number of results to return
func (r ApiListElementsRequest) Limit(limit int32) ApiListElementsRequest {
	r.limit = &limit
	return r
}

// Sort order
func (r ApiListElementsRequest) Order(order SortOrder) ApiListElementsRequest {
	r.order = &order
	return r
}

// Sort field
func (r ApiListElementsRequest) Sort(sort string) ApiListElementsRequest {
	r.sort = &sort
	return r
}

// View trash instead of active records if true
func (r ApiListElementsRequest) Trash(trash int32) ApiListElementsRequest {
	r.trash = &trash
	return r
}

// Filter holidays by their publish state
func (r ApiListElementsRequest) Published(published int32) ApiListElementsRequest {
	r.published = &published
	return r
}

func (r ApiListElementsRequest) Execute() (*ListElements200Response, *http.Response, error) {
	return r.ApiService.ListElementsExecute(r)
}

/*
ListElements List Elements

List Elements

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param version Version ID
 @return ApiListElementsRequest
*/
func (a *ElementsAPIService) ListElements(ctx context.Context, version string) ApiListElementsRequest {
	return ApiListElementsRequest{
		ApiService: a,
		ctx: ctx,
		version: version,
	}
}

// Execute executes the request
//  @return ListElements200Response
func (a *ElementsAPIService) ListElementsExecute(r ApiListElementsRequest) (*ListElements200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListElements200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.ListElements")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/versions/{version}/elements"
	localVarPath = strings.Replace(localVarPath, "{"+"version"+"}", url.PathEscape(parameterValueToString(r.version, "version")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.version) < 26 {
		return localVarReturnValue, nil, reportError("version must have at least 26 elements")
	}
	if strlen(r.version) > 26 {
		return localVarReturnValue, nil, reportError("version must have less than 26 elements")
	}

	if r.name != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "name", r.name, "form", "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	} else {
		var defaultValue int32 = 1
		r.page = &defaultValue
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
		var defaultValue int32 = 20
		r.limit = &defaultValue
	}
	if r.order != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "order", r.order, "form", "")
	}
	if r.sort != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sort", r.sort, "form", "")
	}
	if r.trash != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "trash", r.trash, "form", "")
	}
	if r.published != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "published", r.published, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRestoreAnOptionRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	element string
	option string
}

func (r ApiRestoreAnOptionRequest) Execute() (*ElementOptionProperties, *http.Response, error) {
	return r.ApiService.RestoreAnOptionExecute(r)
}

/*
RestoreAnOption Restore an Option

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param element Element ID
 @param option Option ID
 @return ApiRestoreAnOptionRequest
*/
func (a *ElementsAPIService) RestoreAnOption(ctx context.Context, element string, option string) ApiRestoreAnOptionRequest {
	return ApiRestoreAnOptionRequest{
		ApiService: a,
		ctx: ctx,
		element: element,
		option: option,
	}
}

// Execute executes the request
//  @return ElementOptionProperties
func (a *ElementsAPIService) RestoreAnOptionExecute(r ApiRestoreAnOptionRequest) (*ElementOptionProperties, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ElementOptionProperties
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.RestoreAnOption")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/elements/{element}/options/{option}/restore"
	localVarPath = strings.Replace(localVarPath, "{"+"element"+"}", url.PathEscape(parameterValueToString(r.element, "element")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"option"+"}", url.PathEscape(parameterValueToString(r.option, "option")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.element) < 26 {
		return localVarReturnValue, nil, reportError("element must have at least 26 elements")
	}
	if strlen(r.element) > 26 {
		return localVarReturnValue, nil, reportError("element must have less than 26 elements")
	}
	if strlen(r.option) < 26 {
		return localVarReturnValue, nil, reportError("option must have at least 26 elements")
	}
	if strlen(r.option) > 26 {
		return localVarReturnValue, nil, reportError("option must have less than 26 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateElementRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	version string
	element string
	updateElementRequest *UpdateElementRequest
}

func (r ApiUpdateElementRequest) UpdateElementRequest(updateElementRequest UpdateElementRequest) ApiUpdateElementRequest {
	r.updateElementRequest = &updateElementRequest
	return r
}

func (r ApiUpdateElementRequest) Execute() (*Element, *http.Response, error) {
	return r.ApiService.UpdateElementExecute(r)
}

/*
UpdateElement Update Element

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param version Version ID
 @param element Element ID
 @return ApiUpdateElementRequest
*/
func (a *ElementsAPIService) UpdateElement(ctx context.Context, version string, element string) ApiUpdateElementRequest {
	return ApiUpdateElementRequest{
		ApiService: a,
		ctx: ctx,
		version: version,
		element: element,
	}
}

// Execute executes the request
//  @return Element
func (a *ElementsAPIService) UpdateElementExecute(r ApiUpdateElementRequest) (*Element, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Element
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.UpdateElement")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/versions/{version}/elements/{element}"
	localVarPath = strings.Replace(localVarPath, "{"+"version"+"}", url.PathEscape(parameterValueToString(r.version, "version")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"element"+"}", url.PathEscape(parameterValueToString(r.element, "element")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.version) < 26 {
		return localVarReturnValue, nil, reportError("version must have at least 26 elements")
	}
	if strlen(r.version) > 26 {
		return localVarReturnValue, nil, reportError("version must have less than 26 elements")
	}
	if strlen(r.element) < 26 {
		return localVarReturnValue, nil, reportError("element must have at least 26 elements")
	}
	if strlen(r.element) > 26 {
		return localVarReturnValue, nil, reportError("element must have less than 26 elements")
	}
	if r.updateElementRequest == nil {
		return localVarReturnValue, nil, reportError("updateElementRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateElementRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v InlineObject2
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v InlineObject3
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateOptionRequest struct {
	ctx context.Context
	ApiService *ElementsAPIService
	element string
	option string
	elementOptionParams *ElementOptionParams
}

func (r ApiUpdateOptionRequest) ElementOptionParams(elementOptionParams ElementOptionParams) ApiUpdateOptionRequest {
	r.elementOptionParams = &elementOptionParams
	return r
}

func (r ApiUpdateOptionRequest) Execute() (*ElementOptionProperties, *http.Response, error) {
	return r.ApiService.UpdateOptionExecute(r)
}

/*
UpdateOption Update Option

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param element Element ID
 @param option Option ID
 @return ApiUpdateOptionRequest
*/
func (a *ElementsAPIService) UpdateOption(ctx context.Context, element string, option string) ApiUpdateOptionRequest {
	return ApiUpdateOptionRequest{
		ApiService: a,
		ctx: ctx,
		element: element,
		option: option,
	}
}

// Execute executes the request
//  @return ElementOptionProperties
func (a *ElementsAPIService) UpdateOptionExecute(r ApiUpdateOptionRequest) (*ElementOptionProperties, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ElementOptionProperties
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ElementsAPIService.UpdateOption")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/holidays/elements/{element}/options/{option}"
	localVarPath = strings.Replace(localVarPath, "{"+"element"+"}", url.PathEscape(parameterValueToString(r.element, "element")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"option"+"}", url.PathEscape(parameterValueToString(r.option, "option")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.element) < 26 {
		return localVarReturnValue, nil, reportError("element must have at least 26 elements")
	}
	if strlen(r.element) > 26 {
		return localVarReturnValue, nil, reportError("element must have less than 26 elements")
	}
	if strlen(r.option) < 26 {
		return localVarReturnValue, nil, reportError("option must have at least 26 elements")
	}
	if strlen(r.option) > 26 {
		return localVarReturnValue, nil, reportError("option must have less than 26 elements")
	}
	if r.elementOptionParams == nil {
		return localVarReturnValue, nil, reportError("elementOptionParams is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.elementOptionParams
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v InlineObject3
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v InlineObject2
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
