/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DepartureProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DepartureProperties{}

// DepartureProperties struct for DepartureProperties
type DepartureProperties struct {
	Start time.Time `json:"start"`
	End time.Time `json:"end"`
	RangeType *DepartureRangeType `json:"range_type,omitempty"`
	Inventory Inventory `json:"inventory"`
}

type _DepartureProperties DepartureProperties

// NewDepartureProperties instantiates a new DepartureProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDepartureProperties(start time.Time, end time.Time, inventory Inventory) *DepartureProperties {
	this := DepartureProperties{}
	this.Start = start
	this.End = end
	this.Inventory = inventory
	return &this
}

// NewDeparturePropertiesWithDefaults instantiates a new DepartureProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeparturePropertiesWithDefaults() *DepartureProperties {
	this := DepartureProperties{}
	return &this
}

// GetStart returns the Start field value
func (o *DepartureProperties) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *DepartureProperties) GetStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *DepartureProperties) SetStart(v time.Time) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *DepartureProperties) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *DepartureProperties) GetEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *DepartureProperties) SetEnd(v time.Time) {
	o.End = v
}

// GetRangeType returns the RangeType field value if set, zero value otherwise.
func (o *DepartureProperties) GetRangeType() DepartureRangeType {
	if o == nil || IsNil(o.RangeType) {
		var ret DepartureRangeType
		return ret
	}
	return *o.RangeType
}

// GetRangeTypeOk returns a tuple with the RangeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureProperties) GetRangeTypeOk() (*DepartureRangeType, bool) {
	if o == nil || IsNil(o.RangeType) {
		return nil, false
	}
	return o.RangeType, true
}

// HasRangeType returns a boolean if a field has been set.
func (o *DepartureProperties) HasRangeType() bool {
	if o != nil && !IsNil(o.RangeType) {
		return true
	}

	return false
}

// SetRangeType gets a reference to the given DepartureRangeType and assigns it to the RangeType field.
func (o *DepartureProperties) SetRangeType(v DepartureRangeType) {
	o.RangeType = &v
}

// GetInventory returns the Inventory field value
func (o *DepartureProperties) GetInventory() Inventory {
	if o == nil {
		var ret Inventory
		return ret
	}

	return o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value
// and a boolean to check if the value has been set.
func (o *DepartureProperties) GetInventoryOk() (*Inventory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Inventory, true
}

// SetInventory sets field value
func (o *DepartureProperties) SetInventory(v Inventory) {
	o.Inventory = v
}

func (o DepartureProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DepartureProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	if !IsNil(o.RangeType) {
		toSerialize["range_type"] = o.RangeType
	}
	toSerialize["inventory"] = o.Inventory
	return toSerialize, nil
}

func (o *DepartureProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"start",
		"end",
		"inventory",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDepartureProperties := _DepartureProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDepartureProperties)

	if err != nil {
		return err
	}

	*o = DepartureProperties(varDepartureProperties)

	return err
}

type NullableDepartureProperties struct {
	value *DepartureProperties
	isSet bool
}

func (v NullableDepartureProperties) Get() *DepartureProperties {
	return v.value
}

func (v *NullableDepartureProperties) Set(val *DepartureProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableDepartureProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableDepartureProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDepartureProperties(val *DepartureProperties) *NullableDepartureProperties {
	return &NullableDepartureProperties{value: val, isSet: true}
}

func (v NullableDepartureProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDepartureProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


