/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
)

// checks if the ListItineraries200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListItineraries200Response{}

// ListItineraries200Response struct for ListItineraries200Response
type ListItineraries200Response struct {
	Data []SharedItinerary `json:"data,omitempty"`
}

// NewListItineraries200Response instantiates a new ListItineraries200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListItineraries200Response() *ListItineraries200Response {
	this := ListItineraries200Response{}
	return &this
}

// NewListItineraries200ResponseWithDefaults instantiates a new ListItineraries200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListItineraries200ResponseWithDefaults() *ListItineraries200Response {
	this := ListItineraries200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListItineraries200Response) GetData() []SharedItinerary {
	if o == nil || IsNil(o.Data) {
		var ret []SharedItinerary
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListItineraries200Response) GetDataOk() ([]SharedItinerary, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListItineraries200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []SharedItinerary and assigns it to the Data field.
func (o *ListItineraries200Response) SetData(v []SharedItinerary) {
	o.Data = v
}

func (o ListItineraries200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListItineraries200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListItineraries200Response struct {
	value *ListItineraries200Response
	isSet bool
}

func (v NullableListItineraries200Response) Get() *ListItineraries200Response {
	return v.value
}

func (v *NullableListItineraries200Response) Set(val *ListItineraries200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListItineraries200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListItineraries200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListItineraries200Response(val *ListItineraries200Response) *NullableListItineraries200Response {
	return &NullableListItineraries200Response{value: val, isSet: true}
}

func (v NullableListItineraries200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListItineraries200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


