/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"time"
)

// checks if the DepartureParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DepartureParams{}

// DepartureParams struct for DepartureParams
type DepartureParams struct {
	Start *time.Time `json:"start,omitempty"`
	End *time.Time `json:"end,omitempty"`
	RangeType *DepartureRangeType `json:"range_type,omitempty"`
	Inventory *Inventory `json:"inventory,omitempty"`
}

// NewDepartureParams instantiates a new DepartureParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDepartureParams() *DepartureParams {
	this := DepartureParams{}
	return &this
}

// NewDepartureParamsWithDefaults instantiates a new DepartureParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDepartureParamsWithDefaults() *DepartureParams {
	this := DepartureParams{}
	return &this
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *DepartureParams) GetStart() time.Time {
	if o == nil || IsNil(o.Start) {
		var ret time.Time
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureParams) GetStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *DepartureParams) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given time.Time and assigns it to the Start field.
func (o *DepartureParams) SetStart(v time.Time) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *DepartureParams) GetEnd() time.Time {
	if o == nil || IsNil(o.End) {
		var ret time.Time
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureParams) GetEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *DepartureParams) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given time.Time and assigns it to the End field.
func (o *DepartureParams) SetEnd(v time.Time) {
	o.End = &v
}

// GetRangeType returns the RangeType field value if set, zero value otherwise.
func (o *DepartureParams) GetRangeType() DepartureRangeType {
	if o == nil || IsNil(o.RangeType) {
		var ret DepartureRangeType
		return ret
	}
	return *o.RangeType
}

// GetRangeTypeOk returns a tuple with the RangeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureParams) GetRangeTypeOk() (*DepartureRangeType, bool) {
	if o == nil || IsNil(o.RangeType) {
		return nil, false
	}
	return o.RangeType, true
}

// HasRangeType returns a boolean if a field has been set.
func (o *DepartureParams) HasRangeType() bool {
	if o != nil && !IsNil(o.RangeType) {
		return true
	}

	return false
}

// SetRangeType gets a reference to the given DepartureRangeType and assigns it to the RangeType field.
func (o *DepartureParams) SetRangeType(v DepartureRangeType) {
	o.RangeType = &v
}

// GetInventory returns the Inventory field value if set, zero value otherwise.
func (o *DepartureParams) GetInventory() Inventory {
	if o == nil || IsNil(o.Inventory) {
		var ret Inventory
		return ret
	}
	return *o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureParams) GetInventoryOk() (*Inventory, bool) {
	if o == nil || IsNil(o.Inventory) {
		return nil, false
	}
	return o.Inventory, true
}

// HasInventory returns a boolean if a field has been set.
func (o *DepartureParams) HasInventory() bool {
	if o != nil && !IsNil(o.Inventory) {
		return true
	}

	return false
}

// SetInventory gets a reference to the given Inventory and assigns it to the Inventory field.
func (o *DepartureParams) SetInventory(v Inventory) {
	o.Inventory = &v
}

func (o DepartureParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DepartureParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.RangeType) {
		toSerialize["range_type"] = o.RangeType
	}
	if !IsNil(o.Inventory) {
		toSerialize["inventory"] = o.Inventory
	}
	return toSerialize, nil
}

type NullableDepartureParams struct {
	value *DepartureParams
	isSet bool
}

func (v NullableDepartureParams) Get() *DepartureParams {
	return v.value
}

func (v *NullableDepartureParams) Set(val *DepartureParams) {
	v.value = val
	v.isSet = true
}

func (v NullableDepartureParams) IsSet() bool {
	return v.isSet
}

func (v *NullableDepartureParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDepartureParams(val *DepartureParams) *NullableDepartureParams {
	return &NullableDepartureParams{value: val, isSet: true}
}

func (v NullableDepartureParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDepartureParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


