/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateHolidayRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateHolidayRequest{}

// CreateHolidayRequest struct for CreateHolidayRequest
type CreateHolidayRequest struct {
	// Holiday Name
	Name string `json:"name"`
	// Holiday Code
	Code string `json:"code" validate:"regexp=^[A-Z0-9][A-Z0-9-]*$"`
	Introduction *string `json:"introduction,omitempty"`
	// Holiday description (HTML Content)
	Description *string `json:"description,omitempty"`
	// Determines if the holiday is publicly viewable.
	Published *bool `json:"published,omitempty"`
}

type _CreateHolidayRequest CreateHolidayRequest

// NewCreateHolidayRequest instantiates a new CreateHolidayRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateHolidayRequest(name string, code string) *CreateHolidayRequest {
	this := CreateHolidayRequest{}
	this.Name = name
	this.Code = code
	var published bool = false
	this.Published = &published
	return &this
}

// NewCreateHolidayRequestWithDefaults instantiates a new CreateHolidayRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateHolidayRequestWithDefaults() *CreateHolidayRequest {
	this := CreateHolidayRequest{}
	var published bool = false
	this.Published = &published
	return &this
}

// GetName returns the Name field value
func (o *CreateHolidayRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateHolidayRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateHolidayRequest) SetName(v string) {
	o.Name = v
}

// GetCode returns the Code field value
func (o *CreateHolidayRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *CreateHolidayRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CreateHolidayRequest) SetCode(v string) {
	o.Code = v
}

// GetIntroduction returns the Introduction field value if set, zero value otherwise.
func (o *CreateHolidayRequest) GetIntroduction() string {
	if o == nil || IsNil(o.Introduction) {
		var ret string
		return ret
	}
	return *o.Introduction
}

// GetIntroductionOk returns a tuple with the Introduction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHolidayRequest) GetIntroductionOk() (*string, bool) {
	if o == nil || IsNil(o.Introduction) {
		return nil, false
	}
	return o.Introduction, true
}

// HasIntroduction returns a boolean if a field has been set.
func (o *CreateHolidayRequest) HasIntroduction() bool {
	if o != nil && !IsNil(o.Introduction) {
		return true
	}

	return false
}

// SetIntroduction gets a reference to the given string and assigns it to the Introduction field.
func (o *CreateHolidayRequest) SetIntroduction(v string) {
	o.Introduction = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateHolidayRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHolidayRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateHolidayRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateHolidayRequest) SetDescription(v string) {
	o.Description = &v
}

// GetPublished returns the Published field value if set, zero value otherwise.
func (o *CreateHolidayRequest) GetPublished() bool {
	if o == nil || IsNil(o.Published) {
		var ret bool
		return ret
	}
	return *o.Published
}

// GetPublishedOk returns a tuple with the Published field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHolidayRequest) GetPublishedOk() (*bool, bool) {
	if o == nil || IsNil(o.Published) {
		return nil, false
	}
	return o.Published, true
}

// HasPublished returns a boolean if a field has been set.
func (o *CreateHolidayRequest) HasPublished() bool {
	if o != nil && !IsNil(o.Published) {
		return true
	}

	return false
}

// SetPublished gets a reference to the given bool and assigns it to the Published field.
func (o *CreateHolidayRequest) SetPublished(v bool) {
	o.Published = &v
}

func (o CreateHolidayRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateHolidayRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["code"] = o.Code
	if !IsNil(o.Introduction) {
		toSerialize["introduction"] = o.Introduction
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Published) {
		toSerialize["published"] = o.Published
	}
	return toSerialize, nil
}

func (o *CreateHolidayRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateHolidayRequest := _CreateHolidayRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateHolidayRequest)

	if err != nil {
		return err
	}

	*o = CreateHolidayRequest(varCreateHolidayRequest)

	return err
}

type NullableCreateHolidayRequest struct {
	value *CreateHolidayRequest
	isSet bool
}

func (v NullableCreateHolidayRequest) Get() *CreateHolidayRequest {
	return v.value
}

func (v *NullableCreateHolidayRequest) Set(val *CreateHolidayRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateHolidayRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateHolidayRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateHolidayRequest(val *CreateHolidayRequest) *NullableCreateHolidayRequest {
	return &NullableCreateHolidayRequest{value: val, isSet: true}
}

func (v NullableCreateHolidayRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateHolidayRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


