/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
)

// checks if the Organization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Organization{}

// Organization struct for Organization
type Organization struct {
	// A unique identifier. Unique system-wide to a single entity. Consists of 26 alphanumeric characters. 
	Id *string `json:"id,omitempty"`
	// Organization's RezKit ID
	RezkitId *string `json:"rezkit_id,omitempty"`
	// Organization Name
	Name *string `json:"name,omitempty"`
	// List of presently available currencies. 
	Currencies []string `json:"currencies,omitempty"`
	DepositDefaults *OrganizationDepositDefaults `json:"deposit_defaults,omitempty"`
}

// NewOrganization instantiates a new Organization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganization() *Organization {
	this := Organization{}
	return &this
}

// NewOrganizationWithDefaults instantiates a new Organization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationWithDefaults() *Organization {
	this := Organization{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Organization) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Organization) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Organization) SetId(v string) {
	o.Id = &v
}

// GetRezkitId returns the RezkitId field value if set, zero value otherwise.
func (o *Organization) GetRezkitId() string {
	if o == nil || IsNil(o.RezkitId) {
		var ret string
		return ret
	}
	return *o.RezkitId
}

// GetRezkitIdOk returns a tuple with the RezkitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetRezkitIdOk() (*string, bool) {
	if o == nil || IsNil(o.RezkitId) {
		return nil, false
	}
	return o.RezkitId, true
}

// HasRezkitId returns a boolean if a field has been set.
func (o *Organization) HasRezkitId() bool {
	if o != nil && !IsNil(o.RezkitId) {
		return true
	}

	return false
}

// SetRezkitId gets a reference to the given string and assigns it to the RezkitId field.
func (o *Organization) SetRezkitId(v string) {
	o.RezkitId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Organization) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Organization) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Organization) SetName(v string) {
	o.Name = &v
}

// GetCurrencies returns the Currencies field value if set, zero value otherwise.
func (o *Organization) GetCurrencies() []string {
	if o == nil || IsNil(o.Currencies) {
		var ret []string
		return ret
	}
	return o.Currencies
}

// GetCurrenciesOk returns a tuple with the Currencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetCurrenciesOk() ([]string, bool) {
	if o == nil || IsNil(o.Currencies) {
		return nil, false
	}
	return o.Currencies, true
}

// HasCurrencies returns a boolean if a field has been set.
func (o *Organization) HasCurrencies() bool {
	if o != nil && !IsNil(o.Currencies) {
		return true
	}

	return false
}

// SetCurrencies gets a reference to the given []string and assigns it to the Currencies field.
func (o *Organization) SetCurrencies(v []string) {
	o.Currencies = v
}

// GetDepositDefaults returns the DepositDefaults field value if set, zero value otherwise.
func (o *Organization) GetDepositDefaults() OrganizationDepositDefaults {
	if o == nil || IsNil(o.DepositDefaults) {
		var ret OrganizationDepositDefaults
		return ret
	}
	return *o.DepositDefaults
}

// GetDepositDefaultsOk returns a tuple with the DepositDefaults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetDepositDefaultsOk() (*OrganizationDepositDefaults, bool) {
	if o == nil || IsNil(o.DepositDefaults) {
		return nil, false
	}
	return o.DepositDefaults, true
}

// HasDepositDefaults returns a boolean if a field has been set.
func (o *Organization) HasDepositDefaults() bool {
	if o != nil && !IsNil(o.DepositDefaults) {
		return true
	}

	return false
}

// SetDepositDefaults gets a reference to the given OrganizationDepositDefaults and assigns it to the DepositDefaults field.
func (o *Organization) SetDepositDefaults(v OrganizationDepositDefaults) {
	o.DepositDefaults = &v
}

func (o Organization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Organization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.RezkitId) {
		toSerialize["rezkit_id"] = o.RezkitId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Currencies) {
		toSerialize["currencies"] = o.Currencies
	}
	if !IsNil(o.DepositDefaults) {
		toSerialize["deposit_defaults"] = o.DepositDefaults
	}
	return toSerialize, nil
}

type NullableOrganization struct {
	value *Organization
	isSet bool
}

func (v NullableOrganization) Get() *Organization {
	return v.value
}

func (v *NullableOrganization) Set(val *Organization) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganization(val *Organization) *NullableOrganization {
	return &NullableOrganization{value: val, isSet: true}
}

func (v NullableOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


