/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
)

// checks if the ListHolidays200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListHolidays200Response{}

// ListHolidays200Response struct for ListHolidays200Response
type ListHolidays200Response struct {
	// Total number of matching holidays
	Total *int32 `json:"total,omitempty"`
	// Current page number
	CurrentPage *int32 `json:"current_page,omitempty"`
	// Total number of pages
	LastPage *int32 `json:"last_page,omitempty"`
	// Index of the first result on the current page.
	From *int32 `json:"from,omitempty"`
	// Index of the last result on the current page.
	To *int32 `json:"to,omitempty"`
	// Matching Holidays
	Data []Holiday `json:"data,omitempty"`
}

// NewListHolidays200Response instantiates a new ListHolidays200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListHolidays200Response() *ListHolidays200Response {
	this := ListHolidays200Response{}
	return &this
}

// NewListHolidays200ResponseWithDefaults instantiates a new ListHolidays200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListHolidays200ResponseWithDefaults() *ListHolidays200Response {
	this := ListHolidays200Response{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListHolidays200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListHolidays200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListHolidays200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListHolidays200Response) SetTotal(v int32) {
	o.Total = &v
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *ListHolidays200Response) GetCurrentPage() int32 {
	if o == nil || IsNil(o.CurrentPage) {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListHolidays200Response) GetCurrentPageOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentPage) {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *ListHolidays200Response) HasCurrentPage() bool {
	if o != nil && !IsNil(o.CurrentPage) {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *ListHolidays200Response) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetLastPage returns the LastPage field value if set, zero value otherwise.
func (o *ListHolidays200Response) GetLastPage() int32 {
	if o == nil || IsNil(o.LastPage) {
		var ret int32
		return ret
	}
	return *o.LastPage
}

// GetLastPageOk returns a tuple with the LastPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListHolidays200Response) GetLastPageOk() (*int32, bool) {
	if o == nil || IsNil(o.LastPage) {
		return nil, false
	}
	return o.LastPage, true
}

// HasLastPage returns a boolean if a field has been set.
func (o *ListHolidays200Response) HasLastPage() bool {
	if o != nil && !IsNil(o.LastPage) {
		return true
	}

	return false
}

// SetLastPage gets a reference to the given int32 and assigns it to the LastPage field.
func (o *ListHolidays200Response) SetLastPage(v int32) {
	o.LastPage = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *ListHolidays200Response) GetFrom() int32 {
	if o == nil || IsNil(o.From) {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListHolidays200Response) GetFromOk() (*int32, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *ListHolidays200Response) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *ListHolidays200Response) SetFrom(v int32) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *ListHolidays200Response) GetTo() int32 {
	if o == nil || IsNil(o.To) {
		var ret int32
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListHolidays200Response) GetToOk() (*int32, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *ListHolidays200Response) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given int32 and assigns it to the To field.
func (o *ListHolidays200Response) SetTo(v int32) {
	o.To = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListHolidays200Response) GetData() []Holiday {
	if o == nil || IsNil(o.Data) {
		var ret []Holiday
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListHolidays200Response) GetDataOk() ([]Holiday, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListHolidays200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Holiday and assigns it to the Data field.
func (o *ListHolidays200Response) SetData(v []Holiday) {
	o.Data = v
}

func (o ListHolidays200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListHolidays200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.CurrentPage) {
		toSerialize["current_page"] = o.CurrentPage
	}
	if !IsNil(o.LastPage) {
		toSerialize["last_page"] = o.LastPage
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListHolidays200Response struct {
	value *ListHolidays200Response
	isSet bool
}

func (v NullableListHolidays200Response) Get() *ListHolidays200Response {
	return v.value
}

func (v *NullableListHolidays200Response) Set(val *ListHolidays200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListHolidays200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListHolidays200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListHolidays200Response(val *ListHolidays200Response) *NullableListHolidays200Response {
	return &NullableListHolidays200Response{value: val, isSet: true}
}

func (v NullableListHolidays200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListHolidays200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


