/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ItineraryEntryProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItineraryEntryProperties{}

// ItineraryEntryProperties struct for ItineraryEntryProperties
type ItineraryEntryProperties struct {
	StartDay int32 `json:"start_day"`
	EndDay int32 `json:"end_day"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	Introduction *string `json:"introduction,omitempty"`
	Published *bool `json:"published,omitempty"`
	IncludesBreakfast *bool `json:"includes_breakfast,omitempty"`
	IncludesLunch *bool `json:"includes_lunch,omitempty"`
	IncludesDinner *bool `json:"includes_dinner,omitempty"`
}

type _ItineraryEntryProperties ItineraryEntryProperties

// NewItineraryEntryProperties instantiates a new ItineraryEntryProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItineraryEntryProperties(startDay int32, endDay int32, title string) *ItineraryEntryProperties {
	this := ItineraryEntryProperties{}
	this.StartDay = startDay
	this.EndDay = endDay
	this.Title = title
	return &this
}

// NewItineraryEntryPropertiesWithDefaults instantiates a new ItineraryEntryProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItineraryEntryPropertiesWithDefaults() *ItineraryEntryProperties {
	this := ItineraryEntryProperties{}
	return &this
}

// GetStartDay returns the StartDay field value
func (o *ItineraryEntryProperties) GetStartDay() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartDay
}

// GetStartDayOk returns a tuple with the StartDay field value
// and a boolean to check if the value has been set.
func (o *ItineraryEntryProperties) GetStartDayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartDay, true
}

// SetStartDay sets field value
func (o *ItineraryEntryProperties) SetStartDay(v int32) {
	o.StartDay = v
}

// GetEndDay returns the EndDay field value
func (o *ItineraryEntryProperties) GetEndDay() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndDay
}

// GetEndDayOk returns a tuple with the EndDay field value
// and a boolean to check if the value has been set.
func (o *ItineraryEntryProperties) GetEndDayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndDay, true
}

// SetEndDay sets field value
func (o *ItineraryEntryProperties) SetEndDay(v int32) {
	o.EndDay = v
}

// GetTitle returns the Title field value
func (o *ItineraryEntryProperties) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ItineraryEntryProperties) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ItineraryEntryProperties) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ItineraryEntryProperties) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItineraryEntryProperties) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ItineraryEntryProperties) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ItineraryEntryProperties) SetDescription(v string) {
	o.Description = &v
}

// GetIntroduction returns the Introduction field value if set, zero value otherwise.
func (o *ItineraryEntryProperties) GetIntroduction() string {
	if o == nil || IsNil(o.Introduction) {
		var ret string
		return ret
	}
	return *o.Introduction
}

// GetIntroductionOk returns a tuple with the Introduction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItineraryEntryProperties) GetIntroductionOk() (*string, bool) {
	if o == nil || IsNil(o.Introduction) {
		return nil, false
	}
	return o.Introduction, true
}

// HasIntroduction returns a boolean if a field has been set.
func (o *ItineraryEntryProperties) HasIntroduction() bool {
	if o != nil && !IsNil(o.Introduction) {
		return true
	}

	return false
}

// SetIntroduction gets a reference to the given string and assigns it to the Introduction field.
func (o *ItineraryEntryProperties) SetIntroduction(v string) {
	o.Introduction = &v
}

// GetPublished returns the Published field value if set, zero value otherwise.
func (o *ItineraryEntryProperties) GetPublished() bool {
	if o == nil || IsNil(o.Published) {
		var ret bool
		return ret
	}
	return *o.Published
}

// GetPublishedOk returns a tuple with the Published field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItineraryEntryProperties) GetPublishedOk() (*bool, bool) {
	if o == nil || IsNil(o.Published) {
		return nil, false
	}
	return o.Published, true
}

// HasPublished returns a boolean if a field has been set.
func (o *ItineraryEntryProperties) HasPublished() bool {
	if o != nil && !IsNil(o.Published) {
		return true
	}

	return false
}

// SetPublished gets a reference to the given bool and assigns it to the Published field.
func (o *ItineraryEntryProperties) SetPublished(v bool) {
	o.Published = &v
}

// GetIncludesBreakfast returns the IncludesBreakfast field value if set, zero value otherwise.
func (o *ItineraryEntryProperties) GetIncludesBreakfast() bool {
	if o == nil || IsNil(o.IncludesBreakfast) {
		var ret bool
		return ret
	}
	return *o.IncludesBreakfast
}

// GetIncludesBreakfastOk returns a tuple with the IncludesBreakfast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItineraryEntryProperties) GetIncludesBreakfastOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludesBreakfast) {
		return nil, false
	}
	return o.IncludesBreakfast, true
}

// HasIncludesBreakfast returns a boolean if a field has been set.
func (o *ItineraryEntryProperties) HasIncludesBreakfast() bool {
	if o != nil && !IsNil(o.IncludesBreakfast) {
		return true
	}

	return false
}

// SetIncludesBreakfast gets a reference to the given bool and assigns it to the IncludesBreakfast field.
func (o *ItineraryEntryProperties) SetIncludesBreakfast(v bool) {
	o.IncludesBreakfast = &v
}

// GetIncludesLunch returns the IncludesLunch field value if set, zero value otherwise.
func (o *ItineraryEntryProperties) GetIncludesLunch() bool {
	if o == nil || IsNil(o.IncludesLunch) {
		var ret bool
		return ret
	}
	return *o.IncludesLunch
}

// GetIncludesLunchOk returns a tuple with the IncludesLunch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItineraryEntryProperties) GetIncludesLunchOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludesLunch) {
		return nil, false
	}
	return o.IncludesLunch, true
}

// HasIncludesLunch returns a boolean if a field has been set.
func (o *ItineraryEntryProperties) HasIncludesLunch() bool {
	if o != nil && !IsNil(o.IncludesLunch) {
		return true
	}

	return false
}

// SetIncludesLunch gets a reference to the given bool and assigns it to the IncludesLunch field.
func (o *ItineraryEntryProperties) SetIncludesLunch(v bool) {
	o.IncludesLunch = &v
}

// GetIncludesDinner returns the IncludesDinner field value if set, zero value otherwise.
func (o *ItineraryEntryProperties) GetIncludesDinner() bool {
	if o == nil || IsNil(o.IncludesDinner) {
		var ret bool
		return ret
	}
	return *o.IncludesDinner
}

// GetIncludesDinnerOk returns a tuple with the IncludesDinner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItineraryEntryProperties) GetIncludesDinnerOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludesDinner) {
		return nil, false
	}
	return o.IncludesDinner, true
}

// HasIncludesDinner returns a boolean if a field has been set.
func (o *ItineraryEntryProperties) HasIncludesDinner() bool {
	if o != nil && !IsNil(o.IncludesDinner) {
		return true
	}

	return false
}

// SetIncludesDinner gets a reference to the given bool and assigns it to the IncludesDinner field.
func (o *ItineraryEntryProperties) SetIncludesDinner(v bool) {
	o.IncludesDinner = &v
}

func (o ItineraryEntryProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItineraryEntryProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start_day"] = o.StartDay
	toSerialize["end_day"] = o.EndDay
	toSerialize["title"] = o.Title
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Introduction) {
		toSerialize["introduction"] = o.Introduction
	}
	if !IsNil(o.Published) {
		toSerialize["published"] = o.Published
	}
	if !IsNil(o.IncludesBreakfast) {
		toSerialize["includes_breakfast"] = o.IncludesBreakfast
	}
	if !IsNil(o.IncludesLunch) {
		toSerialize["includes_lunch"] = o.IncludesLunch
	}
	if !IsNil(o.IncludesDinner) {
		toSerialize["includes_dinner"] = o.IncludesDinner
	}
	return toSerialize, nil
}

func (o *ItineraryEntryProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"start_day",
		"end_day",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varItineraryEntryProperties := _ItineraryEntryProperties{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varItineraryEntryProperties)

	if err != nil {
		return err
	}

	*o = ItineraryEntryProperties(varItineraryEntryProperties)

	return err
}

type NullableItineraryEntryProperties struct {
	value *ItineraryEntryProperties
	isSet bool
}

func (v NullableItineraryEntryProperties) Get() *ItineraryEntryProperties {
	return v.value
}

func (v *NullableItineraryEntryProperties) Set(val *ItineraryEntryProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableItineraryEntryProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableItineraryEntryProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItineraryEntryProperties(val *ItineraryEntryProperties) *NullableItineraryEntryProperties {
	return &NullableItineraryEntryProperties{value: val, isSet: true}
}

func (v NullableItineraryEntryProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItineraryEntryProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


