/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
)

// checks if the ElementOptionParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ElementOptionParams{}

// ElementOptionParams struct for ElementOptionParams
type ElementOptionParams struct {
	// A unique identifier. Unique system-wide to a single entity. Consists of 26 alphanumeric characters. 
	CategoryId *string `json:"category_id,omitempty"`
	Name *string `json:"name,omitempty"`
	Occupancy *Occupancy `json:"occupancy,omitempty"`
	PriceUnit *PriceUnit `json:"price_unit,omitempty"`
	Published *bool `json:"published,omitempty"`
	WebBookable *bool `json:"web_bookable,omitempty"`
	IsLead *bool `json:"is_lead,omitempty"`
}

// NewElementOptionParams instantiates a new ElementOptionParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewElementOptionParams() *ElementOptionParams {
	this := ElementOptionParams{}
	var published bool = true
	this.Published = &published
	var webBookable bool = true
	this.WebBookable = &webBookable
	var isLead bool = true
	this.IsLead = &isLead
	return &this
}

// NewElementOptionParamsWithDefaults instantiates a new ElementOptionParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewElementOptionParamsWithDefaults() *ElementOptionParams {
	this := ElementOptionParams{}
	var published bool = true
	this.Published = &published
	var webBookable bool = true
	this.WebBookable = &webBookable
	var isLead bool = true
	this.IsLead = &isLead
	return &this
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *ElementOptionParams) GetCategoryId() string {
	if o == nil || IsNil(o.CategoryId) {
		var ret string
		return ret
	}
	return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ElementOptionParams) GetCategoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.CategoryId) {
		return nil, false
	}
	return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *ElementOptionParams) HasCategoryId() bool {
	if o != nil && !IsNil(o.CategoryId) {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given string and assigns it to the CategoryId field.
func (o *ElementOptionParams) SetCategoryId(v string) {
	o.CategoryId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ElementOptionParams) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ElementOptionParams) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ElementOptionParams) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ElementOptionParams) SetName(v string) {
	o.Name = &v
}

// GetOccupancy returns the Occupancy field value if set, zero value otherwise.
func (o *ElementOptionParams) GetOccupancy() Occupancy {
	if o == nil || IsNil(o.Occupancy) {
		var ret Occupancy
		return ret
	}
	return *o.Occupancy
}

// GetOccupancyOk returns a tuple with the Occupancy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ElementOptionParams) GetOccupancyOk() (*Occupancy, bool) {
	if o == nil || IsNil(o.Occupancy) {
		return nil, false
	}
	return o.Occupancy, true
}

// HasOccupancy returns a boolean if a field has been set.
func (o *ElementOptionParams) HasOccupancy() bool {
	if o != nil && !IsNil(o.Occupancy) {
		return true
	}

	return false
}

// SetOccupancy gets a reference to the given Occupancy and assigns it to the Occupancy field.
func (o *ElementOptionParams) SetOccupancy(v Occupancy) {
	o.Occupancy = &v
}

// GetPriceUnit returns the PriceUnit field value if set, zero value otherwise.
func (o *ElementOptionParams) GetPriceUnit() PriceUnit {
	if o == nil || IsNil(o.PriceUnit) {
		var ret PriceUnit
		return ret
	}
	return *o.PriceUnit
}

// GetPriceUnitOk returns a tuple with the PriceUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ElementOptionParams) GetPriceUnitOk() (*PriceUnit, bool) {
	if o == nil || IsNil(o.PriceUnit) {
		return nil, false
	}
	return o.PriceUnit, true
}

// HasPriceUnit returns a boolean if a field has been set.
func (o *ElementOptionParams) HasPriceUnit() bool {
	if o != nil && !IsNil(o.PriceUnit) {
		return true
	}

	return false
}

// SetPriceUnit gets a reference to the given PriceUnit and assigns it to the PriceUnit field.
func (o *ElementOptionParams) SetPriceUnit(v PriceUnit) {
	o.PriceUnit = &v
}

// GetPublished returns the Published field value if set, zero value otherwise.
func (o *ElementOptionParams) GetPublished() bool {
	if o == nil || IsNil(o.Published) {
		var ret bool
		return ret
	}
	return *o.Published
}

// GetPublishedOk returns a tuple with the Published field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ElementOptionParams) GetPublishedOk() (*bool, bool) {
	if o == nil || IsNil(o.Published) {
		return nil, false
	}
	return o.Published, true
}

// HasPublished returns a boolean if a field has been set.
func (o *ElementOptionParams) HasPublished() bool {
	if o != nil && !IsNil(o.Published) {
		return true
	}

	return false
}

// SetPublished gets a reference to the given bool and assigns it to the Published field.
func (o *ElementOptionParams) SetPublished(v bool) {
	o.Published = &v
}

// GetWebBookable returns the WebBookable field value if set, zero value otherwise.
func (o *ElementOptionParams) GetWebBookable() bool {
	if o == nil || IsNil(o.WebBookable) {
		var ret bool
		return ret
	}
	return *o.WebBookable
}

// GetWebBookableOk returns a tuple with the WebBookable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ElementOptionParams) GetWebBookableOk() (*bool, bool) {
	if o == nil || IsNil(o.WebBookable) {
		return nil, false
	}
	return o.WebBookable, true
}

// HasWebBookable returns a boolean if a field has been set.
func (o *ElementOptionParams) HasWebBookable() bool {
	if o != nil && !IsNil(o.WebBookable) {
		return true
	}

	return false
}

// SetWebBookable gets a reference to the given bool and assigns it to the WebBookable field.
func (o *ElementOptionParams) SetWebBookable(v bool) {
	o.WebBookable = &v
}

// GetIsLead returns the IsLead field value if set, zero value otherwise.
func (o *ElementOptionParams) GetIsLead() bool {
	if o == nil || IsNil(o.IsLead) {
		var ret bool
		return ret
	}
	return *o.IsLead
}

// GetIsLeadOk returns a tuple with the IsLead field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ElementOptionParams) GetIsLeadOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLead) {
		return nil, false
	}
	return o.IsLead, true
}

// HasIsLead returns a boolean if a field has been set.
func (o *ElementOptionParams) HasIsLead() bool {
	if o != nil && !IsNil(o.IsLead) {
		return true
	}

	return false
}

// SetIsLead gets a reference to the given bool and assigns it to the IsLead field.
func (o *ElementOptionParams) SetIsLead(v bool) {
	o.IsLead = &v
}

func (o ElementOptionParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ElementOptionParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CategoryId) {
		toSerialize["category_id"] = o.CategoryId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Occupancy) {
		toSerialize["occupancy"] = o.Occupancy
	}
	if !IsNil(o.PriceUnit) {
		toSerialize["price_unit"] = o.PriceUnit
	}
	if !IsNil(o.Published) {
		toSerialize["published"] = o.Published
	}
	if !IsNil(o.WebBookable) {
		toSerialize["web_bookable"] = o.WebBookable
	}
	if !IsNil(o.IsLead) {
		toSerialize["is_lead"] = o.IsLead
	}
	return toSerialize, nil
}

type NullableElementOptionParams struct {
	value *ElementOptionParams
	isSet bool
}

func (v NullableElementOptionParams) Get() *ElementOptionParams {
	return v.value
}

func (v *NullableElementOptionParams) Set(val *ElementOptionParams) {
	v.value = val
	v.isSet = true
}

func (v NullableElementOptionParams) IsSet() bool {
	return v.isSet
}

func (v *NullableElementOptionParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableElementOptionParams(val *ElementOptionParams) *NullableElementOptionParams {
	return &NullableElementOptionParams{value: val, isSet: true}
}

func (v NullableElementOptionParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableElementOptionParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


