/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
)

// checks if the UpdatePriceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePriceRequest{}

// UpdatePriceRequest struct for UpdatePriceRequest
type UpdatePriceRequest struct {
	// Set the price value
	Value *float32 `json:"value,omitempty"`
	// Set the deposit value. Remove the deposit and revert to default calculation by setting to null.
	Deposit NullableFloat32 `json:"deposit,omitempty"`
	OnSale *bool `json:"on_sale,omitempty"`
}

// NewUpdatePriceRequest instantiates a new UpdatePriceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePriceRequest() *UpdatePriceRequest {
	this := UpdatePriceRequest{}
	return &this
}

// NewUpdatePriceRequestWithDefaults instantiates a new UpdatePriceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePriceRequestWithDefaults() *UpdatePriceRequest {
	this := UpdatePriceRequest{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UpdatePriceRequest) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePriceRequest) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UpdatePriceRequest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *UpdatePriceRequest) SetValue(v float32) {
	o.Value = &v
}

// GetDeposit returns the Deposit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatePriceRequest) GetDeposit() float32 {
	if o == nil || IsNil(o.Deposit.Get()) {
		var ret float32
		return ret
	}
	return *o.Deposit.Get()
}

// GetDepositOk returns a tuple with the Deposit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatePriceRequest) GetDepositOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deposit.Get(), o.Deposit.IsSet()
}

// HasDeposit returns a boolean if a field has been set.
func (o *UpdatePriceRequest) HasDeposit() bool {
	if o != nil && o.Deposit.IsSet() {
		return true
	}

	return false
}

// SetDeposit gets a reference to the given NullableFloat32 and assigns it to the Deposit field.
func (o *UpdatePriceRequest) SetDeposit(v float32) {
	o.Deposit.Set(&v)
}
// SetDepositNil sets the value for Deposit to be an explicit nil
func (o *UpdatePriceRequest) SetDepositNil() {
	o.Deposit.Set(nil)
}

// UnsetDeposit ensures that no value is present for Deposit, not even an explicit nil
func (o *UpdatePriceRequest) UnsetDeposit() {
	o.Deposit.Unset()
}

// GetOnSale returns the OnSale field value if set, zero value otherwise.
func (o *UpdatePriceRequest) GetOnSale() bool {
	if o == nil || IsNil(o.OnSale) {
		var ret bool
		return ret
	}
	return *o.OnSale
}

// GetOnSaleOk returns a tuple with the OnSale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePriceRequest) GetOnSaleOk() (*bool, bool) {
	if o == nil || IsNil(o.OnSale) {
		return nil, false
	}
	return o.OnSale, true
}

// HasOnSale returns a boolean if a field has been set.
func (o *UpdatePriceRequest) HasOnSale() bool {
	if o != nil && !IsNil(o.OnSale) {
		return true
	}

	return false
}

// SetOnSale gets a reference to the given bool and assigns it to the OnSale field.
func (o *UpdatePriceRequest) SetOnSale(v bool) {
	o.OnSale = &v
}

func (o UpdatePriceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePriceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if o.Deposit.IsSet() {
		toSerialize["deposit"] = o.Deposit.Get()
	}
	if !IsNil(o.OnSale) {
		toSerialize["on_sale"] = o.OnSale
	}
	return toSerialize, nil
}

type NullableUpdatePriceRequest struct {
	value *UpdatePriceRequest
	isSet bool
}

func (v NullableUpdatePriceRequest) Get() *UpdatePriceRequest {
	return v.value
}

func (v *NullableUpdatePriceRequest) Set(val *UpdatePriceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePriceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePriceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePriceRequest(val *UpdatePriceRequest) *NullableUpdatePriceRequest {
	return &NullableUpdatePriceRequest{value: val, isSet: true}
}

func (v NullableUpdatePriceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePriceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


