/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
)

// checks if the PriceDeposit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceDeposit{}

// PriceDeposit struct for PriceDeposit
type PriceDeposit struct {
	// Determines if the given deposit amount has been calculated via a global rule
	Calculated *bool `json:"calculated,omitempty"`
	// Deposit payment required to confirm a reservation.
	Value *float32 `json:"value,omitempty"`
}

// NewPriceDeposit instantiates a new PriceDeposit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceDeposit() *PriceDeposit {
	this := PriceDeposit{}
	return &this
}

// NewPriceDepositWithDefaults instantiates a new PriceDeposit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceDepositWithDefaults() *PriceDeposit {
	this := PriceDeposit{}
	return &this
}

// GetCalculated returns the Calculated field value if set, zero value otherwise.
func (o *PriceDeposit) GetCalculated() bool {
	if o == nil || IsNil(o.Calculated) {
		var ret bool
		return ret
	}
	return *o.Calculated
}

// GetCalculatedOk returns a tuple with the Calculated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceDeposit) GetCalculatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Calculated) {
		return nil, false
	}
	return o.Calculated, true
}

// HasCalculated returns a boolean if a field has been set.
func (o *PriceDeposit) HasCalculated() bool {
	if o != nil && !IsNil(o.Calculated) {
		return true
	}

	return false
}

// SetCalculated gets a reference to the given bool and assigns it to the Calculated field.
func (o *PriceDeposit) SetCalculated(v bool) {
	o.Calculated = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *PriceDeposit) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceDeposit) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *PriceDeposit) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *PriceDeposit) SetValue(v float32) {
	o.Value = &v
}

func (o PriceDeposit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceDeposit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Calculated) {
		toSerialize["calculated"] = o.Calculated
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullablePriceDeposit struct {
	value *PriceDeposit
	isSet bool
}

func (v NullablePriceDeposit) Get() *PriceDeposit {
	return v.value
}

func (v *NullablePriceDeposit) Set(val *PriceDeposit) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceDeposit) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceDeposit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceDeposit(val *PriceDeposit) *NullablePriceDeposit {
	return &NullablePriceDeposit{value: val, isSet: true}
}

func (v NullablePriceDeposit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceDeposit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


