/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"time"
)

// checks if the Element type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Element{}

// Element struct for Element
type Element struct {
	// A unique identifier. Unique system-wide to a single entity. Consists of 26 alphanumeric characters. 
	Id *string `json:"id,omitempty"`
	// Creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Timestamp of most recent update
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Timestamp of the item's deletion. Null if the item is not deleted.
	DeletedAt NullableTime `json:"deleted_at,omitempty"`
	// A unique identifier. Unique system-wide to a single entity. Consists of 26 alphanumeric characters. 
	VersionId *string `json:"version_id,omitempty"`
	Category *Category `json:"category,omitempty"`
	Name *string `json:"name,omitempty"`
	IsPackage *bool `json:"is_package,omitempty"`
	Published *bool `json:"published,omitempty"`
	DefaultInventory *Inventory `json:"default_inventory,omitempty"`
	// Rule for balance payment due relative to departure date. No balance rule specified, global default applies.
	BalanceDue NullableInt32 `json:"balance_due,omitempty"`
	// Available options for the element. All options for an element share the same inventory. 
	Options []ElementOptionProperties `json:"options,omitempty"`
}

// NewElement instantiates a new Element object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewElement() *Element {
	this := Element{}
	return &this
}

// NewElementWithDefaults instantiates a new Element object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewElementWithDefaults() *Element {
	this := Element{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Element) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Element) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Element) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Element) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Element) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Element) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Element) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Element) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Element) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Element) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Element) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *Element) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableTime and assigns it to the DeletedAt field.
func (o *Element) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}
// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *Element) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *Element) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *Element) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *Element) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *Element) SetVersionId(v string) {
	o.VersionId = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *Element) GetCategory() Category {
	if o == nil || IsNil(o.Category) {
		var ret Category
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetCategoryOk() (*Category, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *Element) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given Category and assigns it to the Category field.
func (o *Element) SetCategory(v Category) {
	o.Category = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Element) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Element) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Element) SetName(v string) {
	o.Name = &v
}

// GetIsPackage returns the IsPackage field value if set, zero value otherwise.
func (o *Element) GetIsPackage() bool {
	if o == nil || IsNil(o.IsPackage) {
		var ret bool
		return ret
	}
	return *o.IsPackage
}

// GetIsPackageOk returns a tuple with the IsPackage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetIsPackageOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPackage) {
		return nil, false
	}
	return o.IsPackage, true
}

// HasIsPackage returns a boolean if a field has been set.
func (o *Element) HasIsPackage() bool {
	if o != nil && !IsNil(o.IsPackage) {
		return true
	}

	return false
}

// SetIsPackage gets a reference to the given bool and assigns it to the IsPackage field.
func (o *Element) SetIsPackage(v bool) {
	o.IsPackage = &v
}

// GetPublished returns the Published field value if set, zero value otherwise.
func (o *Element) GetPublished() bool {
	if o == nil || IsNil(o.Published) {
		var ret bool
		return ret
	}
	return *o.Published
}

// GetPublishedOk returns a tuple with the Published field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetPublishedOk() (*bool, bool) {
	if o == nil || IsNil(o.Published) {
		return nil, false
	}
	return o.Published, true
}

// HasPublished returns a boolean if a field has been set.
func (o *Element) HasPublished() bool {
	if o != nil && !IsNil(o.Published) {
		return true
	}

	return false
}

// SetPublished gets a reference to the given bool and assigns it to the Published field.
func (o *Element) SetPublished(v bool) {
	o.Published = &v
}

// GetDefaultInventory returns the DefaultInventory field value if set, zero value otherwise.
func (o *Element) GetDefaultInventory() Inventory {
	if o == nil || IsNil(o.DefaultInventory) {
		var ret Inventory
		return ret
	}
	return *o.DefaultInventory
}

// GetDefaultInventoryOk returns a tuple with the DefaultInventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetDefaultInventoryOk() (*Inventory, bool) {
	if o == nil || IsNil(o.DefaultInventory) {
		return nil, false
	}
	return o.DefaultInventory, true
}

// HasDefaultInventory returns a boolean if a field has been set.
func (o *Element) HasDefaultInventory() bool {
	if o != nil && !IsNil(o.DefaultInventory) {
		return true
	}

	return false
}

// SetDefaultInventory gets a reference to the given Inventory and assigns it to the DefaultInventory field.
func (o *Element) SetDefaultInventory(v Inventory) {
	o.DefaultInventory = &v
}

// GetBalanceDue returns the BalanceDue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Element) GetBalanceDue() int32 {
	if o == nil || IsNil(o.BalanceDue.Get()) {
		var ret int32
		return ret
	}
	return *o.BalanceDue.Get()
}

// GetBalanceDueOk returns a tuple with the BalanceDue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Element) GetBalanceDueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BalanceDue.Get(), o.BalanceDue.IsSet()
}

// HasBalanceDue returns a boolean if a field has been set.
func (o *Element) HasBalanceDue() bool {
	if o != nil && o.BalanceDue.IsSet() {
		return true
	}

	return false
}

// SetBalanceDue gets a reference to the given NullableInt32 and assigns it to the BalanceDue field.
func (o *Element) SetBalanceDue(v int32) {
	o.BalanceDue.Set(&v)
}
// SetBalanceDueNil sets the value for BalanceDue to be an explicit nil
func (o *Element) SetBalanceDueNil() {
	o.BalanceDue.Set(nil)
}

// UnsetBalanceDue ensures that no value is present for BalanceDue, not even an explicit nil
func (o *Element) UnsetBalanceDue() {
	o.BalanceDue.Unset()
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *Element) GetOptions() []ElementOptionProperties {
	if o == nil || IsNil(o.Options) {
		var ret []ElementOptionProperties
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetOptionsOk() ([]ElementOptionProperties, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *Element) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []ElementOptionProperties and assigns it to the Options field.
func (o *Element) SetOptions(v []ElementOptionProperties) {
	o.Options = v
}

func (o Element) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Element) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deleted_at"] = o.DeletedAt.Get()
	}
	if !IsNil(o.VersionId) {
		toSerialize["version_id"] = o.VersionId
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.IsPackage) {
		toSerialize["is_package"] = o.IsPackage
	}
	if !IsNil(o.Published) {
		toSerialize["published"] = o.Published
	}
	if !IsNil(o.DefaultInventory) {
		toSerialize["default_inventory"] = o.DefaultInventory
	}
	if o.BalanceDue.IsSet() {
		toSerialize["balance_due"] = o.BalanceDue.Get()
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableElement struct {
	value *Element
	isSet bool
}

func (v NullableElement) Get() *Element {
	return v.value
}

func (v *NullableElement) Set(val *Element) {
	v.value = val
	v.isSet = true
}

func (v NullableElement) IsSet() bool {
	return v.isSet
}

func (v *NullableElement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableElement(val *Element) *NullableElement {
	return &NullableElement{value: val, isSet: true}
}

func (v NullableElement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableElement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


