/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// UpdateFieldRequest - struct for UpdateFieldRequest
type UpdateFieldRequest struct {
	UpdateNumericField *UpdateNumericField
	UpdateTextField *UpdateTextField
}

// UpdateNumericFieldAsUpdateFieldRequest is a convenience function that returns UpdateNumericField wrapped in UpdateFieldRequest
func UpdateNumericFieldAsUpdateFieldRequest(v *UpdateNumericField) UpdateFieldRequest {
	return UpdateFieldRequest{
		UpdateNumericField: v,
	}
}

// UpdateTextFieldAsUpdateFieldRequest is a convenience function that returns UpdateTextField wrapped in UpdateFieldRequest
func UpdateTextFieldAsUpdateFieldRequest(v *UpdateTextField) UpdateFieldRequest {
	return UpdateFieldRequest{
		UpdateTextField: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *UpdateFieldRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into UpdateNumericField
	err = newStrictDecoder(data).Decode(&dst.UpdateNumericField)
	if err == nil {
		jsonUpdateNumericField, _ := json.Marshal(dst.UpdateNumericField)
		if string(jsonUpdateNumericField) == "{}" { // empty struct
			dst.UpdateNumericField = nil
		} else {
			if err = validator.Validate(dst.UpdateNumericField); err != nil {
				dst.UpdateNumericField = nil
			} else {
				match++
			}
		}
	} else {
		dst.UpdateNumericField = nil
	}

	// try to unmarshal data into UpdateTextField
	err = newStrictDecoder(data).Decode(&dst.UpdateTextField)
	if err == nil {
		jsonUpdateTextField, _ := json.Marshal(dst.UpdateTextField)
		if string(jsonUpdateTextField) == "{}" { // empty struct
			dst.UpdateTextField = nil
		} else {
			if err = validator.Validate(dst.UpdateTextField); err != nil {
				dst.UpdateTextField = nil
			} else {
				match++
			}
		}
	} else {
		dst.UpdateTextField = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.UpdateNumericField = nil
		dst.UpdateTextField = nil

		return fmt.Errorf("data matches more than one schema in oneOf(UpdateFieldRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(UpdateFieldRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpdateFieldRequest) MarshalJSON() ([]byte, error) {
	if src.UpdateNumericField != nil {
		return json.Marshal(&src.UpdateNumericField)
	}

	if src.UpdateTextField != nil {
		return json.Marshal(&src.UpdateTextField)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UpdateFieldRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.UpdateNumericField != nil {
		return obj.UpdateNumericField
	}

	if obj.UpdateTextField != nil {
		return obj.UpdateTextField
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj UpdateFieldRequest) GetActualInstanceValue() (interface{}) {
	if obj.UpdateNumericField != nil {
		return *obj.UpdateNumericField
	}

	if obj.UpdateTextField != nil {
		return *obj.UpdateTextField
	}

	// all schemas are nil
	return nil
}

type NullableUpdateFieldRequest struct {
	value *UpdateFieldRequest
	isSet bool
}

func (v NullableUpdateFieldRequest) Get() *UpdateFieldRequest {
	return v.value
}

func (v *NullableUpdateFieldRequest) Set(val *UpdateFieldRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFieldRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFieldRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFieldRequest(val *UpdateFieldRequest) *NullableUpdateFieldRequest {
	return &NullableUpdateFieldRequest{value: val, isSet: true}
}

func (v NullableUpdateFieldRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFieldRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


