/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"time"
)

// checks if the DepartureElement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DepartureElement{}

// DepartureElement struct for DepartureElement
type DepartureElement struct {
	// A unique identifier. Unique system-wide to a single entity. Consists of 26 alphanumeric characters. 
	Id *string `json:"id,omitempty"`
	// Creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Timestamp of most recent update
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Timestamp of the item's deletion. Null if the item is not deleted.
	DeletedAt NullableTime `json:"deleted_at,omitempty"`
	Inventory *Inventory `json:"inventory,omitempty"`
	Element *DepartureElementElement `json:"element,omitempty"`
	BalanceDue *DepartureElementBalanceDue `json:"balance_due,omitempty"`
	Options []DepartureElementOptionsInner `json:"options,omitempty"`
}

// NewDepartureElement instantiates a new DepartureElement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDepartureElement() *DepartureElement {
	this := DepartureElement{}
	return &this
}

// NewDepartureElementWithDefaults instantiates a new DepartureElement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDepartureElementWithDefaults() *DepartureElement {
	this := DepartureElement{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DepartureElement) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureElement) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DepartureElement) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DepartureElement) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DepartureElement) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureElement) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DepartureElement) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DepartureElement) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DepartureElement) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureElement) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DepartureElement) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *DepartureElement) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DepartureElement) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DepartureElement) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *DepartureElement) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableTime and assigns it to the DeletedAt field.
func (o *DepartureElement) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}
// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *DepartureElement) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *DepartureElement) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetInventory returns the Inventory field value if set, zero value otherwise.
func (o *DepartureElement) GetInventory() Inventory {
	if o == nil || IsNil(o.Inventory) {
		var ret Inventory
		return ret
	}
	return *o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureElement) GetInventoryOk() (*Inventory, bool) {
	if o == nil || IsNil(o.Inventory) {
		return nil, false
	}
	return o.Inventory, true
}

// HasInventory returns a boolean if a field has been set.
func (o *DepartureElement) HasInventory() bool {
	if o != nil && !IsNil(o.Inventory) {
		return true
	}

	return false
}

// SetInventory gets a reference to the given Inventory and assigns it to the Inventory field.
func (o *DepartureElement) SetInventory(v Inventory) {
	o.Inventory = &v
}

// GetElement returns the Element field value if set, zero value otherwise.
func (o *DepartureElement) GetElement() DepartureElementElement {
	if o == nil || IsNil(o.Element) {
		var ret DepartureElementElement
		return ret
	}
	return *o.Element
}

// GetElementOk returns a tuple with the Element field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureElement) GetElementOk() (*DepartureElementElement, bool) {
	if o == nil || IsNil(o.Element) {
		return nil, false
	}
	return o.Element, true
}

// HasElement returns a boolean if a field has been set.
func (o *DepartureElement) HasElement() bool {
	if o != nil && !IsNil(o.Element) {
		return true
	}

	return false
}

// SetElement gets a reference to the given DepartureElementElement and assigns it to the Element field.
func (o *DepartureElement) SetElement(v DepartureElementElement) {
	o.Element = &v
}

// GetBalanceDue returns the BalanceDue field value if set, zero value otherwise.
func (o *DepartureElement) GetBalanceDue() DepartureElementBalanceDue {
	if o == nil || IsNil(o.BalanceDue) {
		var ret DepartureElementBalanceDue
		return ret
	}
	return *o.BalanceDue
}

// GetBalanceDueOk returns a tuple with the BalanceDue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureElement) GetBalanceDueOk() (*DepartureElementBalanceDue, bool) {
	if o == nil || IsNil(o.BalanceDue) {
		return nil, false
	}
	return o.BalanceDue, true
}

// HasBalanceDue returns a boolean if a field has been set.
func (o *DepartureElement) HasBalanceDue() bool {
	if o != nil && !IsNil(o.BalanceDue) {
		return true
	}

	return false
}

// SetBalanceDue gets a reference to the given DepartureElementBalanceDue and assigns it to the BalanceDue field.
func (o *DepartureElement) SetBalanceDue(v DepartureElementBalanceDue) {
	o.BalanceDue = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *DepartureElement) GetOptions() []DepartureElementOptionsInner {
	if o == nil || IsNil(o.Options) {
		var ret []DepartureElementOptionsInner
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepartureElement) GetOptionsOk() ([]DepartureElementOptionsInner, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *DepartureElement) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []DepartureElementOptionsInner and assigns it to the Options field.
func (o *DepartureElement) SetOptions(v []DepartureElementOptionsInner) {
	o.Options = v
}

func (o DepartureElement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DepartureElement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deleted_at"] = o.DeletedAt.Get()
	}
	if !IsNil(o.Inventory) {
		toSerialize["inventory"] = o.Inventory
	}
	if !IsNil(o.Element) {
		toSerialize["element"] = o.Element
	}
	if !IsNil(o.BalanceDue) {
		toSerialize["balance_due"] = o.BalanceDue
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableDepartureElement struct {
	value *DepartureElement
	isSet bool
}

func (v NullableDepartureElement) Get() *DepartureElement {
	return v.value
}

func (v *NullableDepartureElement) Set(val *DepartureElement) {
	v.value = val
	v.isSet = true
}

func (v NullableDepartureElement) IsSet() bool {
	return v.isSet
}

func (v *NullableDepartureElement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDepartureElement(val *DepartureElement) *NullableDepartureElement {
	return &NullableDepartureElement{value: val, isSet: true}
}

func (v NullableDepartureElement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDepartureElement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


