/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOrganizationSettingsRequestDepositDefaults type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrganizationSettingsRequestDepositDefaults{}

// UpdateOrganizationSettingsRequestDepositDefaults struct for UpdateOrganizationSettingsRequestDepositDefaults
type UpdateOrganizationSettingsRequestDepositDefaults struct {
	// Default percentage rate to apply as a deposit to all prices with no deposit value set
	Percentage float32 `json:"percentage"`
	// Number of days before departure that a balance is due by default unless a specific date is set.
	BalanceDue float32 `json:"balance_due"`
}

type _UpdateOrganizationSettingsRequestDepositDefaults UpdateOrganizationSettingsRequestDepositDefaults

// NewUpdateOrganizationSettingsRequestDepositDefaults instantiates a new UpdateOrganizationSettingsRequestDepositDefaults object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrganizationSettingsRequestDepositDefaults(percentage float32, balanceDue float32) *UpdateOrganizationSettingsRequestDepositDefaults {
	this := UpdateOrganizationSettingsRequestDepositDefaults{}
	this.Percentage = percentage
	this.BalanceDue = balanceDue
	return &this
}

// NewUpdateOrganizationSettingsRequestDepositDefaultsWithDefaults instantiates a new UpdateOrganizationSettingsRequestDepositDefaults object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrganizationSettingsRequestDepositDefaultsWithDefaults() *UpdateOrganizationSettingsRequestDepositDefaults {
	this := UpdateOrganizationSettingsRequestDepositDefaults{}
	return &this
}

// GetPercentage returns the Percentage field value
func (o *UpdateOrganizationSettingsRequestDepositDefaults) GetPercentage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationSettingsRequestDepositDefaults) GetPercentageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percentage, true
}

// SetPercentage sets field value
func (o *UpdateOrganizationSettingsRequestDepositDefaults) SetPercentage(v float32) {
	o.Percentage = v
}

// GetBalanceDue returns the BalanceDue field value
func (o *UpdateOrganizationSettingsRequestDepositDefaults) GetBalanceDue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BalanceDue
}

// GetBalanceDueOk returns a tuple with the BalanceDue field value
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationSettingsRequestDepositDefaults) GetBalanceDueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BalanceDue, true
}

// SetBalanceDue sets field value
func (o *UpdateOrganizationSettingsRequestDepositDefaults) SetBalanceDue(v float32) {
	o.BalanceDue = v
}

func (o UpdateOrganizationSettingsRequestDepositDefaults) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrganizationSettingsRequestDepositDefaults) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["percentage"] = o.Percentage
	toSerialize["balance_due"] = o.BalanceDue
	return toSerialize, nil
}

func (o *UpdateOrganizationSettingsRequestDepositDefaults) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"percentage",
		"balance_due",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOrganizationSettingsRequestDepositDefaults := _UpdateOrganizationSettingsRequestDepositDefaults{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOrganizationSettingsRequestDepositDefaults)

	if err != nil {
		return err
	}

	*o = UpdateOrganizationSettingsRequestDepositDefaults(varUpdateOrganizationSettingsRequestDepositDefaults)

	return err
}

type NullableUpdateOrganizationSettingsRequestDepositDefaults struct {
	value *UpdateOrganizationSettingsRequestDepositDefaults
	isSet bool
}

func (v NullableUpdateOrganizationSettingsRequestDepositDefaults) Get() *UpdateOrganizationSettingsRequestDepositDefaults {
	return v.value
}

func (v *NullableUpdateOrganizationSettingsRequestDepositDefaults) Set(val *UpdateOrganizationSettingsRequestDepositDefaults) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrganizationSettingsRequestDepositDefaults) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrganizationSettingsRequestDepositDefaults) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrganizationSettingsRequestDepositDefaults(val *UpdateOrganizationSettingsRequestDepositDefaults) *NullableUpdateOrganizationSettingsRequestDepositDefaults {
	return &NullableUpdateOrganizationSettingsRequestDepositDefaults{value: val, isSet: true}
}

func (v NullableUpdateOrganizationSettingsRequestDepositDefaults) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrganizationSettingsRequestDepositDefaults) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


