/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Occupancy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Occupancy{}

// Occupancy Occupancy determines the number of passengers which can be allocated to a single reservation. For example a hotel room with a double bed may have an occupancy of exactly two, meaning exactly two passengers must be assigned to the reservation. 
type Occupancy struct {
	// Minimum number of passengers required to book.
	From int32 `json:"from"`
	// Maximum number of passengers bookable per reservation.
	To int32 `json:"to"`
}

type _Occupancy Occupancy

// NewOccupancy instantiates a new Occupancy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOccupancy(from int32, to int32) *Occupancy {
	this := Occupancy{}
	this.From = from
	this.To = to
	return &this
}

// NewOccupancyWithDefaults instantiates a new Occupancy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOccupancyWithDefaults() *Occupancy {
	this := Occupancy{}
	return &this
}

// GetFrom returns the From field value
func (o *Occupancy) GetFrom() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *Occupancy) GetFromOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *Occupancy) SetFrom(v int32) {
	o.From = v
}

// GetTo returns the To field value
func (o *Occupancy) GetTo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *Occupancy) GetToOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *Occupancy) SetTo(v int32) {
	o.To = v
}

func (o Occupancy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Occupancy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	return toSerialize, nil
}

func (o *Occupancy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOccupancy := _Occupancy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOccupancy)

	if err != nil {
		return err
	}

	*o = Occupancy(varOccupancy)

	return err
}

type NullableOccupancy struct {
	value *Occupancy
	isSet bool
}

func (v NullableOccupancy) Get() *Occupancy {
	return v.value
}

func (v *NullableOccupancy) Set(val *Occupancy) {
	v.value = val
	v.isSet = true
}

func (v NullableOccupancy) IsSet() bool {
	return v.isSet
}

func (v *NullableOccupancy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOccupancy(val *Occupancy) *NullableOccupancy {
	return &NullableOccupancy{value: val, isSet: true}
}

func (v NullableOccupancy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOccupancy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


