/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NumberFieldDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NumberFieldDefinition{}

// NumberFieldDefinition struct for NumberFieldDefinition
type NumberFieldDefinition struct {
	// A unique identifier. Unique system-wide to a single entity. Consists of 26 alphanumeric characters. 
	Id string `json:"id"`
	// Field Name
	Name string `json:"name" validate:"regexp=^[a-z][a-z0-9_]*$"`
	// Field group ID
	GroupId string `json:"group_id"`
	Rank *int32 `json:"rank,omitempty"`
	Label string `json:"label"`
	// Determines if this field is required
	Required bool `json:"required"`
	Type string `json:"type"`
	// Minimum allowed value (inclusive)
	MinimumValue *int32 `json:"minimumValue,omitempty"`
	// Maximum allowed value (inclusive)
	MaximumValue *int32 `json:"maximumValue,omitempty"`
	// Decimal places
	Precision int32 `json:"precision"`
}

type _NumberFieldDefinition NumberFieldDefinition

// NewNumberFieldDefinition instantiates a new NumberFieldDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNumberFieldDefinition(id string, name string, groupId string, label string, required bool, type_ string, precision int32) *NumberFieldDefinition {
	this := NumberFieldDefinition{}
	this.Id = id
	this.Name = name
	this.GroupId = groupId
	this.Label = label
	this.Required = required
	this.Type = type_
	this.Precision = precision
	return &this
}

// NewNumberFieldDefinitionWithDefaults instantiates a new NumberFieldDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNumberFieldDefinitionWithDefaults() *NumberFieldDefinition {
	this := NumberFieldDefinition{}
	return &this
}

// GetId returns the Id field value
func (o *NumberFieldDefinition) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NumberFieldDefinition) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *NumberFieldDefinition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NumberFieldDefinition) SetName(v string) {
	o.Name = v
}

// GetGroupId returns the GroupId field value
func (o *NumberFieldDefinition) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *NumberFieldDefinition) SetGroupId(v string) {
	o.GroupId = v
}

// GetRank returns the Rank field value if set, zero value otherwise.
func (o *NumberFieldDefinition) GetRank() int32 {
	if o == nil || IsNil(o.Rank) {
		var ret int32
		return ret
	}
	return *o.Rank
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetRankOk() (*int32, bool) {
	if o == nil || IsNil(o.Rank) {
		return nil, false
	}
	return o.Rank, true
}

// HasRank returns a boolean if a field has been set.
func (o *NumberFieldDefinition) HasRank() bool {
	if o != nil && !IsNil(o.Rank) {
		return true
	}

	return false
}

// SetRank gets a reference to the given int32 and assigns it to the Rank field.
func (o *NumberFieldDefinition) SetRank(v int32) {
	o.Rank = &v
}

// GetLabel returns the Label field value
func (o *NumberFieldDefinition) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *NumberFieldDefinition) SetLabel(v string) {
	o.Label = v
}

// GetRequired returns the Required field value
func (o *NumberFieldDefinition) GetRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Required
}

// GetRequiredOk returns a tuple with the Required field value
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Required, true
}

// SetRequired sets field value
func (o *NumberFieldDefinition) SetRequired(v bool) {
	o.Required = v
}

// GetType returns the Type field value
func (o *NumberFieldDefinition) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NumberFieldDefinition) SetType(v string) {
	o.Type = v
}

// GetMinimumValue returns the MinimumValue field value if set, zero value otherwise.
func (o *NumberFieldDefinition) GetMinimumValue() int32 {
	if o == nil || IsNil(o.MinimumValue) {
		var ret int32
		return ret
	}
	return *o.MinimumValue
}

// GetMinimumValueOk returns a tuple with the MinimumValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetMinimumValueOk() (*int32, bool) {
	if o == nil || IsNil(o.MinimumValue) {
		return nil, false
	}
	return o.MinimumValue, true
}

// HasMinimumValue returns a boolean if a field has been set.
func (o *NumberFieldDefinition) HasMinimumValue() bool {
	if o != nil && !IsNil(o.MinimumValue) {
		return true
	}

	return false
}

// SetMinimumValue gets a reference to the given int32 and assigns it to the MinimumValue field.
func (o *NumberFieldDefinition) SetMinimumValue(v int32) {
	o.MinimumValue = &v
}

// GetMaximumValue returns the MaximumValue field value if set, zero value otherwise.
func (o *NumberFieldDefinition) GetMaximumValue() int32 {
	if o == nil || IsNil(o.MaximumValue) {
		var ret int32
		return ret
	}
	return *o.MaximumValue
}

// GetMaximumValueOk returns a tuple with the MaximumValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetMaximumValueOk() (*int32, bool) {
	if o == nil || IsNil(o.MaximumValue) {
		return nil, false
	}
	return o.MaximumValue, true
}

// HasMaximumValue returns a boolean if a field has been set.
func (o *NumberFieldDefinition) HasMaximumValue() bool {
	if o != nil && !IsNil(o.MaximumValue) {
		return true
	}

	return false
}

// SetMaximumValue gets a reference to the given int32 and assigns it to the MaximumValue field.
func (o *NumberFieldDefinition) SetMaximumValue(v int32) {
	o.MaximumValue = &v
}

// GetPrecision returns the Precision field value
func (o *NumberFieldDefinition) GetPrecision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Precision
}

// GetPrecisionOk returns a tuple with the Precision field value
// and a boolean to check if the value has been set.
func (o *NumberFieldDefinition) GetPrecisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Precision, true
}

// SetPrecision sets field value
func (o *NumberFieldDefinition) SetPrecision(v int32) {
	o.Precision = v
}

func (o NumberFieldDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NumberFieldDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["group_id"] = o.GroupId
	if !IsNil(o.Rank) {
		toSerialize["rank"] = o.Rank
	}
	toSerialize["label"] = o.Label
	toSerialize["required"] = o.Required
	toSerialize["type"] = o.Type
	if !IsNil(o.MinimumValue) {
		toSerialize["minimumValue"] = o.MinimumValue
	}
	if !IsNil(o.MaximumValue) {
		toSerialize["maximumValue"] = o.MaximumValue
	}
	toSerialize["precision"] = o.Precision
	return toSerialize, nil
}

func (o *NumberFieldDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"group_id",
		"label",
		"required",
		"type",
		"precision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNumberFieldDefinition := _NumberFieldDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNumberFieldDefinition)

	if err != nil {
		return err
	}

	*o = NumberFieldDefinition(varNumberFieldDefinition)

	return err
}

type NullableNumberFieldDefinition struct {
	value *NumberFieldDefinition
	isSet bool
}

func (v NullableNumberFieldDefinition) Get() *NumberFieldDefinition {
	return v.value
}

func (v *NullableNumberFieldDefinition) Set(val *NumberFieldDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableNumberFieldDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableNumberFieldDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNumberFieldDefinition(val *NumberFieldDefinition) *NullableNumberFieldDefinition {
	return &NullableNumberFieldDefinition{value: val, isSet: true}
}

func (v NullableNumberFieldDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNumberFieldDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


