/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
)

// checks if the GetFields200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFields200ResponseInner{}

// GetFields200ResponseInner struct for GetFields200ResponseInner
type GetFields200ResponseInner struct {
	// A unique identifier. Unique system-wide to a single entity. Consists of 26 alphanumeric characters. 
	Id *string `json:"id,omitempty"`
	// Field group label
	Label *string `json:"label,omitempty"`
	Rank *int32 `json:"rank,omitempty"`
	Fields []FieldDefinition `json:"fields,omitempty"`
}

// NewGetFields200ResponseInner instantiates a new GetFields200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFields200ResponseInner() *GetFields200ResponseInner {
	this := GetFields200ResponseInner{}
	return &this
}

// NewGetFields200ResponseInnerWithDefaults instantiates a new GetFields200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFields200ResponseInnerWithDefaults() *GetFields200ResponseInner {
	this := GetFields200ResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetFields200ResponseInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFields200ResponseInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetFields200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetFields200ResponseInner) SetId(v string) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *GetFields200ResponseInner) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFields200ResponseInner) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *GetFields200ResponseInner) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *GetFields200ResponseInner) SetLabel(v string) {
	o.Label = &v
}

// GetRank returns the Rank field value if set, zero value otherwise.
func (o *GetFields200ResponseInner) GetRank() int32 {
	if o == nil || IsNil(o.Rank) {
		var ret int32
		return ret
	}
	return *o.Rank
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFields200ResponseInner) GetRankOk() (*int32, bool) {
	if o == nil || IsNil(o.Rank) {
		return nil, false
	}
	return o.Rank, true
}

// HasRank returns a boolean if a field has been set.
func (o *GetFields200ResponseInner) HasRank() bool {
	if o != nil && !IsNil(o.Rank) {
		return true
	}

	return false
}

// SetRank gets a reference to the given int32 and assigns it to the Rank field.
func (o *GetFields200ResponseInner) SetRank(v int32) {
	o.Rank = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *GetFields200ResponseInner) GetFields() []FieldDefinition {
	if o == nil || IsNil(o.Fields) {
		var ret []FieldDefinition
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFields200ResponseInner) GetFieldsOk() ([]FieldDefinition, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *GetFields200ResponseInner) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []FieldDefinition and assigns it to the Fields field.
func (o *GetFields200ResponseInner) SetFields(v []FieldDefinition) {
	o.Fields = v
}

func (o GetFields200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFields200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Rank) {
		toSerialize["rank"] = o.Rank
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

type NullableGetFields200ResponseInner struct {
	value *GetFields200ResponseInner
	isSet bool
}

func (v NullableGetFields200ResponseInner) Get() *GetFields200ResponseInner {
	return v.value
}

func (v *NullableGetFields200ResponseInner) Set(val *GetFields200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFields200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFields200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFields200ResponseInner(val *GetFields200ResponseInner) *NullableGetFields200ResponseInner {
	return &NullableGetFields200ResponseInner{value: val, isSet: true}
}

func (v NullableGetFields200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFields200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


