/*
RezKit Tours Manager

An application for managing small group tour products

API version: 2026.05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tourmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TextFieldDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TextFieldDefinition{}

// TextFieldDefinition struct for TextFieldDefinition
type TextFieldDefinition struct {
	// A unique identifier. Unique system-wide to a single entity. Consists of 26 alphanumeric characters. 
	Id string `json:"id"`
	// Field Name
	Name string `json:"name" validate:"regexp=^[a-z][a-z0-9_]*$"`
	// Field group ID
	GroupId string `json:"group_id"`
	Rank *int32 `json:"rank,omitempty"`
	Label string `json:"label"`
	// Determines if this field is required
	Required bool `json:"required"`
	// ## Field Type  Determines the specific type of field. All the field types for a text field handle string values but the specific `type` value determines the semantic input type used  * `text` - Plain text field * `rich_text` - Rich text editor * `url` - URL field, value must be a valid URL * `color` - Color field, value must a valid hex colour 
	Type string `json:"type"`
	// Minimum value length
	MinLength *int32 `json:"minLength,omitempty"`
	// Minimum value length
	MaxLength *int32 `json:"maxLength,omitempty"`
	// RegEx for field value validation. Applicable only when `type` is `text`
	Format *string `json:"format,omitempty"`
}

type _TextFieldDefinition TextFieldDefinition

// NewTextFieldDefinition instantiates a new TextFieldDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextFieldDefinition(id string, name string, groupId string, label string, required bool, type_ string) *TextFieldDefinition {
	this := TextFieldDefinition{}
	this.Id = id
	this.Name = name
	this.GroupId = groupId
	this.Label = label
	this.Required = required
	this.Type = type_
	return &this
}

// NewTextFieldDefinitionWithDefaults instantiates a new TextFieldDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextFieldDefinitionWithDefaults() *TextFieldDefinition {
	this := TextFieldDefinition{}
	return &this
}

// GetId returns the Id field value
func (o *TextFieldDefinition) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TextFieldDefinition) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TextFieldDefinition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TextFieldDefinition) SetName(v string) {
	o.Name = v
}

// GetGroupId returns the GroupId field value
func (o *TextFieldDefinition) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *TextFieldDefinition) SetGroupId(v string) {
	o.GroupId = v
}

// GetRank returns the Rank field value if set, zero value otherwise.
func (o *TextFieldDefinition) GetRank() int32 {
	if o == nil || IsNil(o.Rank) {
		var ret int32
		return ret
	}
	return *o.Rank
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetRankOk() (*int32, bool) {
	if o == nil || IsNil(o.Rank) {
		return nil, false
	}
	return o.Rank, true
}

// HasRank returns a boolean if a field has been set.
func (o *TextFieldDefinition) HasRank() bool {
	if o != nil && !IsNil(o.Rank) {
		return true
	}

	return false
}

// SetRank gets a reference to the given int32 and assigns it to the Rank field.
func (o *TextFieldDefinition) SetRank(v int32) {
	o.Rank = &v
}

// GetLabel returns the Label field value
func (o *TextFieldDefinition) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *TextFieldDefinition) SetLabel(v string) {
	o.Label = v
}

// GetRequired returns the Required field value
func (o *TextFieldDefinition) GetRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Required
}

// GetRequiredOk returns a tuple with the Required field value
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Required, true
}

// SetRequired sets field value
func (o *TextFieldDefinition) SetRequired(v bool) {
	o.Required = v
}

// GetType returns the Type field value
func (o *TextFieldDefinition) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TextFieldDefinition) SetType(v string) {
	o.Type = v
}

// GetMinLength returns the MinLength field value if set, zero value otherwise.
func (o *TextFieldDefinition) GetMinLength() int32 {
	if o == nil || IsNil(o.MinLength) {
		var ret int32
		return ret
	}
	return *o.MinLength
}

// GetMinLengthOk returns a tuple with the MinLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetMinLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MinLength) {
		return nil, false
	}
	return o.MinLength, true
}

// HasMinLength returns a boolean if a field has been set.
func (o *TextFieldDefinition) HasMinLength() bool {
	if o != nil && !IsNil(o.MinLength) {
		return true
	}

	return false
}

// SetMinLength gets a reference to the given int32 and assigns it to the MinLength field.
func (o *TextFieldDefinition) SetMinLength(v int32) {
	o.MinLength = &v
}

// GetMaxLength returns the MaxLength field value if set, zero value otherwise.
func (o *TextFieldDefinition) GetMaxLength() int32 {
	if o == nil || IsNil(o.MaxLength) {
		var ret int32
		return ret
	}
	return *o.MaxLength
}

// GetMaxLengthOk returns a tuple with the MaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetMaxLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxLength) {
		return nil, false
	}
	return o.MaxLength, true
}

// HasMaxLength returns a boolean if a field has been set.
func (o *TextFieldDefinition) HasMaxLength() bool {
	if o != nil && !IsNil(o.MaxLength) {
		return true
	}

	return false
}

// SetMaxLength gets a reference to the given int32 and assigns it to the MaxLength field.
func (o *TextFieldDefinition) SetMaxLength(v int32) {
	o.MaxLength = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *TextFieldDefinition) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextFieldDefinition) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *TextFieldDefinition) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *TextFieldDefinition) SetFormat(v string) {
	o.Format = &v
}

func (o TextFieldDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TextFieldDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["group_id"] = o.GroupId
	if !IsNil(o.Rank) {
		toSerialize["rank"] = o.Rank
	}
	toSerialize["label"] = o.Label
	toSerialize["required"] = o.Required
	toSerialize["type"] = o.Type
	if !IsNil(o.MinLength) {
		toSerialize["minLength"] = o.MinLength
	}
	if !IsNil(o.MaxLength) {
		toSerialize["maxLength"] = o.MaxLength
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	return toSerialize, nil
}

func (o *TextFieldDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"group_id",
		"label",
		"required",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTextFieldDefinition := _TextFieldDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTextFieldDefinition)

	if err != nil {
		return err
	}

	*o = TextFieldDefinition(varTextFieldDefinition)

	return err
}

type NullableTextFieldDefinition struct {
	value *TextFieldDefinition
	isSet bool
}

func (v NullableTextFieldDefinition) Get() *TextFieldDefinition {
	return v.value
}

func (v *NullableTextFieldDefinition) Set(val *TextFieldDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableTextFieldDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableTextFieldDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextFieldDefinition(val *TextFieldDefinition) *NullableTextFieldDefinition {
	return &NullableTextFieldDefinition{value: val, isSet: true}
}

func (v NullableTextFieldDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextFieldDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


